NUM_DICT = {0: 'nono',
            1: 'achiel',
            2: 'ariyo',
            3: 'adek',
            4: "ang'wen",
            5: 'abich',
            6: 'auchiel',
            7: 'abiriyo',
            8: 'aboro',
            9: 'ochiko',
            10: 'apar',
            11: 'apar gachiel',
            12: 'apar gariyo',
            13: 'apar gadek',
            14: "apar gang'wen",
            15: 'apar gabich',
            16: 'apar gauchiel',
            17: 'apar gabiriyo',
            18: 'apar gaboro',
            19: 'apar gochiko',
            20: 'piero ariyo',
            21: 'piero ariyo gachiel',
            22: 'piero ariyo gariyo',
            23: 'piero ariyo gadek',
            24: 'piero ariyo gang’wen',
            25: 'piero ariyo gabich',
            26: 'piero ariyo gauchiel',
            27: 'piero ariyo gabiriyo',
            28: 'piero ariyo gaboro',
            29: 'piero ariyo gochiko',
            30: 'piero adek',
            31: 'piero adek gachiel',
            32: 'piero adek gariyo',
            33: 'piero adek gadek',
            34: 'piero adek gang’wen',
            35: 'piero adek gabich',
            36: 'piero adek gauchiel',
            37: 'piero adek gabiriyo',
            38: 'piero adek gaboro',
            39: 'piero adek gochiko',
            40: 'piero ang’wen',
            41: "piero ang'wen gachiel",
            42: "piero ang'wen gariyo",
            43: "piero ang'wen gadek",
            44: "piero ang'wen gang’wen",
            45: "piero ang'wen gabich",
            46: "piero ang'wen gauchiel",
            47: "piero ang'wen gabiriyo",
            48: "piero ang'wen gaboro",
            49: "piero ang'wen gochiko",
            50: 'piero abich',
            51: 'piero abich gachiel',
            52: 'piero abich gariyo',
            53: 'piero abich gadek',
            54: 'piero abich gang’wen',
            55: 'piero abich gabich',
            56: 'piero abich gauchiel',
            57: 'piero abich gabiriyo',
            58: 'piero abich gaboro',
            59: 'piero abich gochiko',
            60: 'piero auchiel',
            61: 'piero auchiel gachiel',
            62: 'piero auchiel gariyo',
            63: 'piero auchiel gadek',
            64: 'piero auchiel gang’wen',
            65: 'piero auchiel gabich',
            66: 'piero auchiel gauchiel',
            67: 'piero auchiel gabiriyo',
            68: 'piero auchiel gaboro',
            69: 'piero auchiel gochiko',
            70: 'piero abiriyo',
            71: 'piero abiriyo gachiel',
            72: 'piero abiriyo gariyo',
            73: 'piero abiriyo gadek',
            74: 'piero abiriyo gang’wen',
            75: 'piero abiriyo gabich',
            76: 'piero abiriyo gauchiel',
            77: 'piero abiriyo gabiriyo',
            78: 'piero abiriyo gaboro',
            79: 'piero abiriyo gochiko',
            80: 'piero aboro',
            81: 'piero aboro gachiel',
            82: 'piero aboro gariyo',
            83: 'piero aboro gadek',
            84: 'piero aboro gang’wen',
            85: 'piero aboro gabich',
            86: 'piero aboro gauchiel',
            87: 'piero aboro gabiriyo',
            88: 'piero aboro gaboro',
            89: 'piero aboro gochiko',
            90: 'piero ochiko',
            91: 'piero ochiko gachiel',
            92: 'piero ochiko gariyo',
            93: 'piero ochiko gadek',
            94: 'piero ochiko gang’wen',
            95: 'piero ochiko gabich',
            96: 'piero ochiko gauchiel',
            97: 'piero ochiko gabiriyo',
            98: 'piero ochiko gaboro',
            99: 'piero ochiko gochiko',
            100: 'mia achiel',
            101: 'mia achiel gachiel',
            102: 'mia achiel gariyo',
            103: 'mia achiel gadek',
            104: 'mia achiel gang’wen',
            105: 'mia achiel gabich',
            106: 'mia achiel gauchiel',
            107: 'mia achiel gabiriyo',
            108: 'mia achiel gaboro',
            109: 'mia achiel gochiko',
            110: 'mia achiel gapar',
            111: 'mia achiel gapar gachiel',
            112: 'mia achiel gapar gariyo',
            113: 'mia achiel gapar gadek',
            114: 'mia achiel gapar gang’wen',
            115: 'mia achiel gapar gabich',
            116: 'mia achiel gapar gauchiel',
            117: 'mia achiel gapar gabiriyo',
            118: 'mia achiel gapar gaboro',
            119: 'mia achiel gapar gochiko',
            120: 'mia achiel gi piero ariyo',
            121: 'mia achiel gi piero ariyo gachiel',
            122: 'mia achiel gi piero ariyo garyiyo',
            123: 'mia achiel gi piero ariyo gadek',
            124: "mia achiel gi piero ariyo  gang'wen",
            125: 'mia achiel gi piero ariyo  gabich',
            126: 'mia achiel gi piero ariyo gauchiel',
            127: 'mia achiel gi piero ariyo gabiriyo',
            128: 'mia achiel gi piero ariyo gaboro',
            129: 'mia achiel gi piero ariyo gochiko',
            130: 'mia achiel gi piero adek',
            131: 'mia achiel gi piero adek gachiel',
            132: 'mia achiel gi piero adek gariyo',
            133: 'mia achiel gi piero adek gadek',
            134: "mia achiel gi piero adek gang'wen",
            135: 'mia achiel gi piero adek gabich',
            136: 'mia achiel gi piero adek gauchiel',
            137: 'mia achiel gi piero adek gabiriyo',
            138: 'mia achiel gi piero adek gaboro',
            139: 'mia achiel gi piero adek gochiko',
            140: "mia achiel gi piero ang'wen",
            141: "mia achiel gi piero ang'wen gachiel",
            142: "mia achiel gi piero ang'wen gariyo",
            143: "mia achiel gi piero ang'wen gadek",
            144: "mia achiel gi piero ang'wen gang’wen",
            145: "mia achiel gi piero ang'wen gabich",
            146: "mia achiel gi piero ang'wen gauchiel",
            147: "mia achiel gi piero ang'wen gabiriyo",
            148: "mia achiel gi piero ang'wen gaboro",
            149: "mia achiel gi piero ang'wen gochiko",
            150: 'mia chiel gi piero abich'
}

def number_to_luo(number):
    return NUM_DICT[number]
